(define (99-bottles-of-beer)
  (define (bottle-number beer) (if (= beer 0) "No" (number->string beer)))
  (define (bottle-word beer) (if (= beer 1) " bottle" " bottles"))
  (define (bottles-of-beer beer)
    (display (string-append (bottle-number beer) (bottle-word beer) " of beer on the wall\n"))
    (display (string-append (bottle-number beer) (bottle-word beer) " of beer\n"))
    (cond ((zero? beer) (display "Go to the store and buy some more\n")
                        (display "99 bottles of beer on the wall\n"))
          (else (display "Grab one down and pass it around\n")
                (display (string-append (bottle-number (- beer 1)) (bottle-word (- beer 1))
                                        " of beer on the wall\n\n"))
                (bottles-of-beer (- beer 1)))))
  (bottles-of-beer 99))
